spring:
    mongodb:
      embedded:
        version: 3.5.5
    data:
      mongodb:
        host: localhost
        port:  0 # 27017
        database: lib
    messages:
      encoding: UTF-8
mongock:
  #runner-type: "ApplicationRunner"  default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.hystrixapp.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
      read-concern: local
server:
  port: 8085
hystrix:
  command:
    getBookByIdKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    getBooksKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    getSaveBookKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    getUpdateBookKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    getDeleteBookKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    getCommentsBookKey:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
management:
  endpoints:
    web:
      exposure:
        include: "*"